# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en

tone_instructions: |
  Focus on clear, actionable feedback.
  Prefer simple, idiomatic Python with readable, maintainable code.
  Reject or propose changes if the code is unnecessarily complex.
  Point out where code can be simplified or clarified.

reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  walkthrough: false
  request_changes_workflow: true
  tools:
    ruff:
      enabled: true
      config_file: "pyproject.toml"
      level: error
    mypy:
      enabled: true
      strict: true
      config_file: "mypy.ini"
    black:
      enabled: true
      config_file: "pyproject.toml"
    flake8:
      enabled: true
      config_file: ".flake8"
  path_instructions:
    - path: "**/*.py"
      instructions: |
        Favor clarity. If a section is complex, suggest an easier-to-read alternative.
        Enforce type annotations where possible.
        Docstrings should use simple English and describe only what is needed for a user to understand and use the code.

chat:
  auto_reply: true
